version: 2.1

orbs: 
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11.6
    steps:
      - checkout
      - aws-cli/setup
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Lint, audit and test
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
            pylint *.py
            pip-audit
            python -m unittest *.py
      - run:
          name: Build and release
          command: |
            export IMAGE_URL=833465769753.dkr.ecr.ca-central-1.amazonaws.com/binoqlars-schema-analyzer-invoker
            export FUNCTION_NAME=binoqlars-schema-analyzer-invoker
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 833465769753.dkr.ecr.$AWS_REGION.amazonaws.com
            docker build -t $IMAGE_URL .
            docker push $IMAGE_URL
            aws lambda update-function-code --region $AWS_REGION --function-name $FUNCTION_NAME --image-uri $IMAGE_URL:latest

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
